### PR TITLE
ICU-21825 2021a4 Updated Link definition for America/Coral_Harbour

### PR DESCRIPTION
**Pull request by yumaoka**

### CODE REVIEW

**Comment by yumaoka** [comment]
Effective changes is only

Previous version: Link America/Panama America/Coral_Harbour
This version: Link America/Atikokan America/Coral_Harbour

In CLDR timezone data, America/Coral_Harbour is a canonical ID, and America/Atikokan is an alias of America/Coral_Harbour

**Comment by markusicu** [comment]
Question: Why is the tzdata checked in only as a .tar.gz? It seems like it would be useful to check in the text data files as well (in an unversioned path), so that changes in the source are visible.

**Comment by yumaoka** [comment]
>Question: Why is the tzdata checked in only as a .tar.gz? It seems like it would be useful to check in the text data files as well (in an unversioned path), so that changes in the source are visible.

The data build process is designed to take IANA style tzdata archive downloded from IANA site, run make target included in tzdata, produces backward rule file set in a separate directory. So, if you build ICU tzdata, it's more handy to have the tar ball.

I think we are still in exception mode. If this situation continues permanently, then we'd have forked tzdata files managed inn our repository, and update build script to handle them. But I expect this is temporary, so I did not spend time to revise build steps, nor changing the directory structure.

**Comment by markusicu** [comment]
> > Question: Why is the tzdata checked in only as a .tar.gz? It seems like it would be useful to check in the text data files as well (in an unversioned path), so that changes in the source are visible.
> 
> The data build process is designed to take IANA style tzdata archive downloded from IANA site, run make target included in tzdata, produces backward rule file set in a separate directory. So, if you build ICU tzdata, it's more handy to have the tar ball.

That makes sense, but it makes the data really opaque, and it's expensive to keep checking in separate binary files.

**Review by markusicu — APPROVED** [review]
rslgtm

**Comment by markusicu** [comment]
Please take a look at the question about the two tickets in the icu repo PR.

**Pull request merged**
