### PR TITLE
ICU-21325 tz database 2020b updates in icu-data

### PR DESCRIPTION
**Pull request by yumaoka**
https://unicode-org.atlassian.net/browse/ICU-21325

### CODE REVIEW

**Review by markusicu — APPROVED** [review]
rslgtm

**Comment by xnox** [comment]
Is there a build for 2020c please?

**Comment by xnox** [comment]
Or how would I create these files myself for 2020c?

**Comment by xnox** [comment]
Well 2020d?

**Comment by markusicu** [comment]
> Well 2020d?

Yoshito is working on it, see PR #14.

You can always find the latest data at https://github.com/unicode-org/icu-data/tree/master/tzdata/icunew

Also see https://unicode-org.github.io/icu/userguide/datetime/timezone/#updating-the-time-zone-data

**Pull request merged**
