### PR TITLE
ICU-21949 tzdata2022a update

### PR DESCRIPTION
**Pull request by yumaoka**

### CODE REVIEW

**Review by markusicu — APPROVED** [review]
rslgtm

**Comment by jefgen** [comment]
GitHub looks to be stuck on the "Checking for ability to merge automatically…" status.

I'm going to try closing and re-opening this PR to work-around it.

**Comment by jefgen** [comment]
Closing and re-opening the PR didn't help.

I'm going to open a support ticket with GitHub about this...

**Comment by yumaoka** [comment]
@jefgen Thank you for looking into this. I guess I'd create a new PR.

**Comment by jefgen** [comment]
GitHub supported suggested trying to change the branch target, and then changing it back. 
I'll try doing that and see if that helps. If not we might need to make a new PR.

**Comment by yumaoka** [comment]
@jefgen Thanks. It looks it did not work. I'll close this and create a new one.

**Comment by jefgen** [comment]
One other idea/suggestion (if that might be easier than a whole new PR):
Perhaps change the commit message slightly and force-push an update? That might get it unstuck since the commit hash would change.

**Comment by yumaoka** [comment]
@jefgen I did git amend and force push. It resolved the issue!

**Comment by jefgen** [comment]
> I did git amend and force push. It resolved the issue!

Nice! I'm glad that was able to fix the issue!

**Pull request merged**
